/**
 * Phase 2 gates — citation model and verifier (docs/TDD.md §8 Phase 2).
 *
 * The verifier is the trust keystone: claims are generated by a model, citations are
 * checked by code. These tests are adversarial on purpose — a verifier that only passes
 * well-formed input proves nothing.
 */

import { describe, expect, it } from "vitest";

import {
  citeParagraph,
  citeSpan,
  collapseWhitespace,
  deriveConfidence,
  deriveProvisionStatus,
  gateClaims,
  locateQuote,
  sectionById,
  verifyCitation,
  type Citation,
  type Disposition,
  type ParsedDocument,
  type Status,
} from "../src/pipeline/index.js";
import { DOCS, doc } from "./fixtures.js";

/** A citation known to be well-formed, for mutation tests to start from. */
async function goodCitation(): Promise<{ d: ParsedDocument; c: Citation }> {
  const d = await doc(DOCS.order2023A);
  const c = citeParagraph(d, 40);
  if (!c) throw new Error("expected a paragraph to cite");
  return { d, c };
}

describe("citations built from parsed structure always verify", () => {
  it("every paragraph in a document verifies", async () => {
    const d = await doc(DOCS.order2023A);
    let checked = 0;
    for (let i = 0; i < d.paragraphs.length; i++) {
      const c = citeParagraph(d, i);
      expect(c).toBeDefined();
      const r = verifyCitation(d, c!);
      if (!r.ok) throw new Error(`paragraph ${i} failed: ${r.reason} ${r.detail}`);
      expect(r.match).toBe("exact");
      checked++;
    }
    expect(checked).toBe(693); // 683 body + 10 separate opinions
  });

  it("arbitrary spans inside sections verify", async () => {
    const d = await doc(DOCS.order2023A);
    for (const s of d.sections.slice(0, 200)) {
      const start = s.span[0] + 5;
      const end = Math.min(start + 60, s.span[1]);
      if (end <= start) continue;
      const c = citeSpan(d, start, end);
      expect(c).toBeDefined();
      expect(verifyCitation(d, c!).ok).toBe(true);
    }
  });
});

describe("adversarial — mutation must cause rejection", () => {
  it("changing a single character in the quote rejects", async () => {
    const { d, c } = await goodCitation();
    expect(verifyCitation(d, c).ok).toBe(true);

    // Flip one content character in the middle of the quote.
    const mid = Math.floor(c.quote.length / 2);
    const original = c.quote[mid]!;
    const replacement = original === "x" ? "y" : "x";
    const mutated: Citation = {
      ...c,
      quote: c.quote.slice(0, mid) + replacement + c.quote.slice(mid + 1),
    };

    const r = verifyCitation(d, mutated);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("span-mismatch");
  });

  it("rejects at every position — no lucky windows", async () => {
    const { d, c } = await goodCitation();
    // Mutate each non-whitespace position independently; all must reject.
    let tested = 0;
    for (let i = 0; i < Math.min(c.quote.length, 120); i++) {
      const ch = c.quote[i]!;
      if (/\s/.test(ch)) continue; // whitespace-only changes are legitimately tolerated
      const swapped = ch === "a" ? "b" : "a";
      const mutated: Citation = {
        ...c,
        quote: c.quote.slice(0, i) + swapped + c.quote.slice(i + 1),
      };
      expect(verifyCitation(d, mutated).ok).toBe(false);
      tested++;
    }
    expect(tested).toBeGreaterThan(20);
  });

  it("shifting the span by one character rejects", async () => {
    const { d, c } = await goodCitation();
    const shifted: Citation = { ...c, span: [c.span[0] + 1, c.span[1] + 1] };
    expect(verifyCitation(d, shifted).ok).toBe(false);
  });

  it("a fabricated quote rejects", async () => {
    const { d, c } = await goodCitation();
    const fabricated: Citation = {
      ...c,
      quote: "The Commission hereby awards all interconnection customers a full refund.",
    };
    const r = verifyCitation(d, fabricated);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("span-mismatch");
  });

  it("an out-of-bounds span rejects rather than throwing", async () => {
    const { d, c } = await goodCitation();
    for (const span of [
      [-5, 20],
      [10, d.text.length + 100],
      [500, 400],
      [7, 7],
    ] as Array<[number, number]>) {
      const r = verifyCitation(d, { ...c, span });
      expect(r.ok).toBe(false);
      if (!r.ok) expect(r.reason).toBe("out-of-bounds");
    }
  });

  it("an empty quote rejects", async () => {
    const { d, c } = await goodCitation();
    const r = verifyCitation(d, { ...c, quote: "   " });
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("empty-quote");
  });
});

describe("whitespace tolerance is bounded", () => {
  it("accepts a faithful quote that differs only in whitespace", async () => {
    const { d, c } = await goodCitation();
    const reflowed: Citation = { ...c, quote: collapseWhitespace(c.quote) };
    const r = verifyCitation(d, reflowed);
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.match).toBe("normalized");
  });

  it("does NOT let a deleted space merge two words", async () => {
    // normalize("a b") is "a b", never "ab" — so word-boundary changes still reject.
    const { d, c } = await goodCitation();
    const merged: Citation = { ...c, quote: c.quote.replace(/\s+/g, "") };
    expect(verifyCitation(d, merged).ok).toBe(false);
  });

  it("does NOT tolerate a changed word", async () => {
    const { d, c } = await goodCitation();
    const word = c.quote.match(/[A-Za-z]{5,}/);
    expect(word).not.toBeNull();

    // Swap one real word for another. Whitespace normalisation must not rescue this.
    const swapped = c.quote.replace(word![0], "notarealwordhere");
    expect(verifyCitation(d, { ...c, quote: swapped }).ok).toBe(false);
    expect(locateQuote(d, swapped).ok).toBe(false);
  });

  it("does NOT tolerate a modal verb swap — shall vs may", async () => {
    // The distinction between an obligation and a permission is the whole point.
    const d = await doc(DOCS.order2023A);
    const found = locateQuote(d, "Interconnection Customer shall submit");
    const tampered = "Interconnection Customer may submit";
    if (found.ok) {
      const forged = { ...found.citation, quote: tampered };
      expect(verifyCitation(d, forged).ok).toBe(false);
    }
    // And the tampered text must not resolve to the untampered location either.
    const relocated = locateQuote(d, tampered);
    if (relocated.ok) {
      expect(relocated.citation.quote).not.toContain("shall submit");
    }
  });
});

describe("nested sections resolve correctly", () => {
  it("rejects a citation naming one section but pointing into another", async () => {
    // Order No. 2023 contains "Appendix C: Pro forma LGIP" and "Appendix C to LGIA".
    // A citation naming one while pointing into the other must be rejected — the
    // reviewer would otherwise land on text that does not support the claim.
    const d = await doc(DOCS.order2023);
    const appendixCs = d.sections.filter((s) =>
      /^Appendix C\b/i.test(s.headingPath.at(-1) ?? ""),
    );
    expect(appendixCs.length).toBeGreaterThanOrEqual(2);

    const [first, second] = appendixCs;
    const inFirst = citeSpan(d, first!.span[0] + 50, first!.span[0] + 110);
    expect(inFirst).toBeDefined();
    expect(verifyCitation(d, inFirst!).ok).toBe(true);

    // Same span, but relabelled with the other Appendix C's id.
    const mislabelled: Citation = { ...inFirst!, sectionId: second!.id };
    const r = verifyCitation(d, mislabelled);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("section-mismatch");
  });

  it("rejects a citation naming a section that does not exist", async () => {
    const { d, c } = await goodCitation();
    const r = verifyCitation(d, { ...c, sectionId: "999/999/999" });
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("section-mismatch");
  });

  it("resolves a span to the innermost containing section", async () => {
    const d = await doc(DOCS.order2023);
    const deep = d.sections.filter((s) => s.depth >= 3);
    expect(deep.length).toBeGreaterThan(0);
    const s = deep[Math.floor(deep.length / 2)]!;
    const c = citeSpan(d, s.span[0] + 10, s.span[0] + 40);
    expect(c).toBeDefined();
    const resolved = sectionById(d, c!.sectionId);
    expect(resolved!.depth).toBeGreaterThanOrEqual(s.depth);
  });
});

describe("locateQuote — the path model output takes", () => {
  it("locates a genuine quote and builds a verifying citation", async () => {
    const d = await doc(DOCS.order2023A);
    // Take real text from the document so we know it is genuine.
    const source = d.text.slice(200_000, 200_120);
    const r = locateQuote(d, source);
    if (r.ok) {
      expect(verifyCitation(d, r.citation).ok).toBe(true);
    } else {
      // Long slices are usually unique; ambiguity is acceptable, absence is not.
      expect(r.reason).toBe("ambiguous");
    }
  });

  it("rejects a fabricated quote as not-found", async () => {
    const d = await doc(DOCS.order2023A);
    const r = locateQuote(
      d,
      "The Commission hereby abolishes all interconnection deposits, effective immediately.",
    );
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.reason).toBe("not-found");
  });

  it("reports ambiguity rather than silently picking the first hit", async () => {
    const d = await doc(DOCS.order2023A);
    const r = locateQuote(d, "the Commission");
    expect(r.ok).toBe(false);
    if (!r.ok) {
      expect(r.reason).toBe("ambiguous");
      expect(r.occurrences ?? 0).toBeGreaterThan(1);
    }
  });

  it("a section hint can disambiguate a repeated quote", async () => {
    const d = await doc(DOCS.order2023A);
    const wide = locateQuote(d, "the Commission");
    expect(wide.ok).toBe(false); // ambiguous document-wide

    // Within a single small section it may become unique; if so it must verify.
    for (const s of d.sections.filter((x) => x.span[1] - x.span[0] < 4000).slice(0, 60)) {
      const scoped = locateQuote(d, "the Commission", { sectionId: s.id });
      if (scoped.ok) {
        expect(verifyCitation(d, scoped.citation).ok).toBe(true);
        expect(scoped.citation.sectionId).toBe(s.id);
        return;
      }
    }
  });

  it("tolerates whitespace differences when locating", async () => {
    const d = await doc(DOCS.order2023A);
    const raw = d.text.slice(150_000, 150_100);
    const reflowed = collapseWhitespace(raw);
    const r = locateQuote(d, reflowed);
    if (r.ok) {
      expect(["exact", "normalized"]).toContain(r.match);
      expect(verifyCitation(d, r.citation).ok).toBe(true);
    } else {
      expect(r.reason).toBe("ambiguous");
    }
  });
});

describe("the display gate — invariant I2", () => {
  it("suppresses failing claims and passes verified ones", async () => {
    const { d, c } = await goodCitation();
    const good = { text: "A verified claim.", citation: c };
    const bad = {
      text: "A claim with a fabricated citation.",
      citation: { ...c, quote: "text that is definitely not in this document at all" },
    };

    const out = gateClaims(d, [good, bad, good]);
    expect(out.passed).toHaveLength(2);
    expect(out.suppressed).toHaveLength(1);
    expect(out.suppressed[0]!.claim.text).toBe(bad.text);
    expect(out.verificationRate).toBeCloseTo(2 / 3);
  });

  it("suppression is total — a failed claim appears nowhere in passed", async () => {
    const { d, c } = await goodCitation();
    const bad = { text: "bad", citation: { ...c, span: [0, 5] as [number, number] } };
    const out = gateClaims(d, [bad]);
    expect(out.passed).toHaveLength(0);
    expect(out.suppressed).toHaveLength(1);
    // Not downgraded, not flagged for display — absent.
    expect(out.passed.some((p) => p.claim.text === "bad")).toBe(false);
  });

  it("conservation (I1): nothing is dropped", async () => {
    const { d, c } = await goodCitation();
    const claims = [
      { text: "1", citation: c },
      { text: "2", citation: { ...c, quote: "nope not here" } },
      { text: "3", citation: { ...c, sectionId: "nonexistent" } },
      { text: "4", citation: c },
    ];
    const out = gateClaims(d, claims);
    expect(out.passed.length + out.suppressed.length).toBe(claims.length);
  });

  it("reports a verification rate with no labeled data (FR13)", async () => {
    const { d, c } = await goodCitation();
    const out = gateClaims(d, [{ text: "ok", citation: c }]);
    expect(out.verificationRate).toBe(1);
  });

  it("an empty claim set has a defined rate", async () => {
    const d = await doc(DOCS.order2023A);
    expect(gateClaims(d, []).verificationRate).toBe(1);
  });
});

describe("provision-level status derivation", () => {
  const cases: Array<[Status, Disposition | undefined, string]> = [
    ["proposed", undefined, "proposed"],
    ["proposed", "affirmed", "proposed"],
    ["final", "modified", "adopted"],
    ["final", undefined, "adopted"],
    ["amended", "affirmed", "settled"],
    ["amended", "sustained", "settled"],
    ["amended", "clarified", "settled"],
    ["amended", "modified", "adopted"],
    ["amended", "set-aside", "reopened"],
  ];

  it.each(cases)("%s + %s → %s", (status, disposition, expected) => {
    expect(deriveProvisionStatus(status, disposition)).toBe(expected);
  });

  it("an unclassified disposition yields unknown, never a confident status", () => {
    for (const s of ["proposed", "final", "amended"] as Status[]) {
      expect(deriveProvisionStatus(s, "unclassified")).toBe("unknown");
    }
  });

  it("an amended document with no disposition yields unknown", () => {
    expect(deriveProvisionStatus("amended", undefined)).toBe("unknown");
  });
});

describe("confidence derivation", () => {
  it("rule-decided items are high confidence and not escalated", () => {
    expect(deriveConfidence({ decidedBy: "rule" })).toEqual({
      confidence: "high",
      escalated: false,
    });
  });

  it("rule/model disagreement escalates", () => {
    expect(deriveConfidence({ decidedBy: "model", ruleModelAgree: false })).toEqual({
      confidence: "low",
      escalated: true,
    });
  });

  it("out-of-vocabulary output escalates rather than being coerced", () => {
    expect(deriveConfidence({ decidedBy: "model", outOfVocabulary: true })).toEqual({
      confidence: "low",
      escalated: true,
    });
  });

  it("low model confidence escalates", () => {
    expect(deriveConfidence({ decidedBy: "model", modelConfidence: 0.3 })).toEqual({
      confidence: "low",
      escalated: true,
    });
  });

  it("confident model output without a rule to compare is medium, not high", () => {
    expect(deriveConfidence({ decidedBy: "model", modelConfidence: 0.95 })).toEqual({
      confidence: "medium",
      escalated: false,
    });
  });
});
