/**
 * Citation construction, verification, and the display gate.
 *
 * This is the trust keystone (docs/TDD.md §1). Claims are generated by a model;
 * citations are verified by code. A claim whose citation does not match source is
 * SUPPRESSED — not flagged, not downgraded, not shown with a caveat. That is what makes
 * "citation-grade" a mechanical property of the system rather than a promise about model
 * quality.
 *
 * Built in Phase 2, before any model output exists to verify: the gate exists before
 * anything needs gating.
 */

import type {
  Citation,
  MatchKind,
  ParsedDocument,
  Section,
  VerificationResult,
} from "./types.js";

// ---------------------------------------------------------------------------
// Whitespace-normalized index
// ---------------------------------------------------------------------------

interface NormalizedIndex {
  /** Whitespace-collapsed text. */
  text: string;
  /** offsets[i] = offset in the original text of normalized character i. */
  offsets: Int32Array;
}

const normalizedCache = new WeakMap<ParsedDocument, NormalizedIndex>();

function isSpace(ch: string): boolean {
  return ch === " " || ch === "\n" || ch === "\t" || ch === "\r" || ch === "\f";
}

/**
 * Collapse whitespace runs to a single space, retaining a map back to original offsets.
 *
 * Source text carries newlines and indentation from the XML — "non-refundable \n
 * application fee" — so a faithful quotation will differ from the raw text in
 * whitespace alone. Collapsing runs cannot merge or split words, so it cannot let a
 * changed word through: normalize("a b") is "a b", never "ab".
 */
function buildNormalized(text: string): NormalizedIndex {
  const chars = new Array<string>(text.length);
  const offs = new Int32Array(text.length);
  let n = 0;
  let pendingSpace = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    if (isSpace(ch)) {
      pendingSpace = n > 0;
      continue;
    }
    if (pendingSpace) {
      chars[n] = " ";
      offs[n] = i;
      n++;
      pendingSpace = false;
    }
    chars[n] = ch;
    offs[n] = i;
    n++;
  }

  return { text: chars.slice(0, n).join(""), offsets: offs.slice(0, n) };
}

function normalizedIndex(doc: ParsedDocument): NormalizedIndex {
  let idx = normalizedCache.get(doc);
  if (!idx) {
    idx = buildNormalized(doc.text);
    normalizedCache.set(doc, idx);
  }
  return idx;
}

/** Public helper: collapse whitespace the same way the index does. */
export function collapseWhitespace(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

// ---------------------------------------------------------------------------
// Section lookup
// ---------------------------------------------------------------------------

export function sectionById(doc: ParsedDocument, id: string): Section | undefined {
  return doc.sections.find((s) => s.id === id);
}

/** Innermost section containing an offset. */
export function sectionAtOffset(doc: ParsedDocument, offset: number): Section | undefined {
  let best: Section | undefined;
  for (const s of doc.sections) {
    if (s.span[0] <= offset && offset < s.span[1]) {
      if (!best || s.depth > best.depth) best = s;
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// Verification
// ---------------------------------------------------------------------------

/**
 * Verify an existing citation against its document.
 *
 * Checks, in order: the quote is non-empty; the span is in bounds; the text at the span
 * matches the quote (exactly, or after whitespace collapse); and the span actually falls
 * inside the section the citation names.
 *
 * That last check is not redundant. Order No. 2023 contains both "Appendix C: Pro forma
 * LGIP" and "Appendix C to LGIA" — a citation naming one while pointing into the other
 * would send a reviewer to text that does not support the claim.
 */
export function verifyCitation(doc: ParsedDocument, citation: Citation): VerificationResult {
  if (citation.quote.trim() === "") {
    return { ok: false, reason: "empty-quote", detail: "Quote is empty." };
  }

  const [start, end] = citation.span;
  if (start < 0 || end > doc.text.length || end <= start) {
    return {
      ok: false,
      reason: "out-of-bounds",
      detail: `Span [${start}, ${end}) is outside document of length ${doc.text.length}.`,
    };
  }

  const actual = doc.text.slice(start, end);
  let match: MatchKind;
  if (actual === citation.quote) {
    match = "exact";
  } else if (collapseWhitespace(actual) === collapseWhitespace(citation.quote)) {
    match = "normalized";
  } else {
    return {
      ok: false,
      reason: "span-mismatch",
      detail:
        `Text at span does not match quote.\n` +
        `  quote:  ${JSON.stringify(truncate(citation.quote))}\n` +
        `  source: ${JSON.stringify(truncate(actual))}`,
    };
  }

  const section = sectionById(doc, citation.sectionId);
  if (!section) {
    return {
      ok: false,
      reason: "section-mismatch",
      detail: `No section with id "${citation.sectionId}".`,
    };
  }
  if (start < section.span[0] || start >= section.span[1]) {
    return {
      ok: false,
      reason: "section-mismatch",
      detail:
        `Span [${start}, ${end}) is outside section "${citation.sectionId}" ` +
        `(${section.headingPath.at(-1)}) which spans [${section.span[0]}, ${section.span[1]}).`,
    };
  }

  return { ok: true, match, citation };
}

function truncate(s: string, n = 80): string {
  return s.length <= n ? s : `${s.slice(0, n)}…`;
}

// ---------------------------------------------------------------------------
// Locating a quote (the path model output actually takes)
// ---------------------------------------------------------------------------

export interface LocateOptions {
  /** Restrict the search to this section — resolves quotes that recur document-wide. */
  sectionId?: string;
  /** Paragraph number to record on the resulting citation. */
  paragraphNumber?: number | null;
}

/**
 * Find a quote in the document and construct a verified citation for it.
 *
 * This is the path model output actually takes: models reproduce text far more reliably
 * than they produce character offsets, so the model supplies a quote and code computes
 * the span. A quote that appears nowhere is fabricated and rejected. A quote appearing
 * more than once is ambiguous — real text, but not a citation, because it does not
 * identify a location. Ambiguity is reported rather than silently resolved to the first
 * hit.
 */
export function locateQuote(
  doc: ParsedDocument,
  quote: string,
  opts: LocateOptions = {},
): VerificationResult {
  const trimmed = quote.trim();
  if (trimmed === "") {
    return { ok: false, reason: "empty-quote", detail: "Quote is empty." };
  }

  const scope = opts.sectionId ? sectionById(doc, opts.sectionId) : undefined;
  if (opts.sectionId && !scope) {
    return {
      ok: false,
      reason: "section-mismatch",
      detail: `No section with id "${opts.sectionId}".`,
    };
  }

  const lo = scope ? scope.span[0] : 0;
  const hi = scope ? scope.span[1] : doc.text.length;

  // Exact pass first — preferred when available.
  const exact = findAll(doc.text, trimmed, lo, hi, 2);
  if (exact.length === 1) {
    return finish(doc, trimmed, exact[0]!, exact[0]! + trimmed.length, "exact", opts);
  }
  if (exact.length > 1) {
    return {
      ok: false,
      reason: "ambiguous",
      detail: `Quote occurs more than once${scope ? " in the given section" : ""}.`,
      occurrences: countAll(doc.text, trimmed, lo, hi),
    };
  }

  // Normalized pass — the source carries XML whitespace a faithful quote will not.
  const idx = normalizedIndex(doc);
  const needle = collapseWhitespace(trimmed);
  const nLo = originalToNormalized(idx, lo);
  const nHi = originalToNormalized(idx, hi);

  const hits = findAll(idx.text, needle, nLo, nHi, 2);
  if (hits.length === 0) {
    return {
      ok: false,
      reason: "not-found",
      detail: `Quote does not appear${scope ? " in the given section" : " in the document"}.`,
      occurrences: 0,
    };
  }
  if (hits.length > 1) {
    return {
      ok: false,
      reason: "ambiguous",
      detail: `Quote occurs more than once${scope ? " in the given section" : ""}.`,
      occurrences: countAll(idx.text, needle, nLo, nHi),
    };
  }

  const nStart = hits[0]!;
  const nEnd = nStart + needle.length;
  const start = idx.offsets[nStart]!;
  const end = (idx.offsets[nEnd - 1] ?? start) + 1;
  return finish(doc, doc.text.slice(start, end), start, end, "normalized", opts);
}

function finish(
  doc: ParsedDocument,
  quote: string,
  start: number,
  end: number,
  match: MatchKind,
  opts: LocateOptions,
): VerificationResult {
  const section = opts.sectionId
    ? sectionById(doc, opts.sectionId)
    : sectionAtOffset(doc, start);
  if (!section) {
    return {
      ok: false,
      reason: "section-mismatch",
      detail: `Quote at offset ${start} is not inside any section.`,
    };
  }
  return {
    ok: true,
    match,
    citation: {
      frDocNumber: doc.meta.frDocNumber,
      sectionId: section.id,
      paragraphNumber: opts.paragraphNumber ?? null,
      span: [start, end],
      quote,
    },
  };
}

/** Binary search: normalized offset at or after an original offset. */
function originalToNormalized(idx: NormalizedIndex, originalOffset: number): number {
  let lo = 0;
  let hi = idx.offsets.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (idx.offsets[mid]! < originalOffset) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

/** Occurrences of `needle` within [lo, hi), stopping after `limit` hits. */
function findAll(hay: string, needle: string, lo: number, hi: number, limit: number): number[] {
  const out: number[] = [];
  let from = lo;
  while (out.length < limit) {
    const i = hay.indexOf(needle, from);
    if (i === -1 || i + needle.length > hi) break;
    out.push(i);
    from = i + 1;
  }
  return out;
}

function countAll(hay: string, needle: string, lo: number, hi: number): number {
  let n = 0;
  let from = lo;
  for (;;) {
    const i = hay.indexOf(needle, from);
    if (i === -1 || i + needle.length > hi) return n;
    n++;
    from = i + 1;
  }
}

// ---------------------------------------------------------------------------
// The display gate
// ---------------------------------------------------------------------------

export interface Claim {
  /** What the product would tell the user. */
  text: string;
  citation: Citation;
}

export interface GateOutcome<T extends Claim> {
  /** Claims cleared for display. */
  passed: Array<{ claim: T; match: MatchKind }>;
  /** Claims withheld, with the reason. Never rendered. */
  suppressed: Array<{ claim: T; reason: string; detail: string }>;
  /**
   * Share of claims whose citation verified — FR13. Deterministic instrumentation,
   * available with no labeled data.
   */
  verificationRate: number;
}

/**
 * Gate claims for display. Invariant I2: a claim whose citation fails verification is
 * suppressed, not downgraded.
 *
 * Conservation (I1) holds by construction: passed.length + suppressed.length === input.
 */
export function gateClaims<T extends Claim>(
  doc: ParsedDocument,
  claims: readonly T[],
): GateOutcome<T> {
  const passed: GateOutcome<T>["passed"] = [];
  const suppressed: GateOutcome<T>["suppressed"] = [];

  for (const claim of claims) {
    const result = verifyCitation(doc, claim.citation);
    if (result.ok) passed.push({ claim, match: result.match });
    else suppressed.push({ claim, reason: result.reason, detail: result.detail });
  }

  return {
    passed,
    suppressed,
    verificationRate: claims.length === 0 ? 1 : passed.length / claims.length,
  };
}

// ---------------------------------------------------------------------------
// Constructing citations from parsed structure
// ---------------------------------------------------------------------------

/** Build a citation for a whole paragraph. Always verifies — the span comes from the parse. */
export function citeParagraph(
  doc: ParsedDocument,
  paragraphIndex: number,
): Citation | undefined {
  const p = doc.paragraphs[paragraphIndex];
  if (!p) return undefined;
  return {
    frDocNumber: doc.meta.frDocNumber,
    sectionId: p.sectionId,
    paragraphNumber: p.number,
    span: [...p.span] as [number, number],
    quote: doc.text.slice(p.span[0], p.span[1]),
  };
}

/** Build a citation for an arbitrary span, resolving the containing section. */
export function citeSpan(
  doc: ParsedDocument,
  start: number,
  end: number,
  paragraphNumber: number | null = null,
): Citation | undefined {
  const section = sectionAtOffset(doc, start);
  if (!section) return undefined;
  return {
    frDocNumber: doc.meta.frDocNumber,
    sectionId: section.id,
    paragraphNumber,
    span: [start, end],
    quote: doc.text.slice(start, end),
  };
}
